pub mod check;
pub mod completions;
pub mod copy;
mod copy_strategies;
pub mod deploy;
pub mod doctor;
pub mod init;
pub mod jobs;
pub mod r#move;
pub mod remote_copy;
pub mod remove;
pub mod serve;
pub mod update;
